#dictionary
FileTypes: dict =  {
    "exe":"Executables",
    "msi":"Executables",
    "apk":"Executables",
    "torrent":"Torrents",
    "png":"Images",
    "svg":"Images",
    "jpg":"Images",
    "jpeg":"Images",
    "gif":"Images",
    "bmp":"Images",
    "ico":"Images",
    "zip":"Compressed Files",
    "7z":"Compressed Files",
    "rar":"Compressed Files",
    "gz":"Compressed Files",
    "wav":"Audio",
    "mp3":"Audio",
    "flac":"Audio",
    "m4a":"Audio",
    "ogg":"Audio",
    "mpa":"Audio",
    "mid":"Audio",
    "midi":"Audio",
    "mkv":"Videos",
    "avi":"Videos",
    "mp4":"Videos",
    "webm":"Videos",
    "stl":"3DModels",
    "pdf":"Documents",
    "pptx":"Documents",
    "html":"Documents",
    "md":"Documents",
    "txt":"Documents",
    "docx":"Documents",
    "doc":"Documents",
    "xml":"Documents",
    "xls":"Documents",
    "xlsx":"Documents",
    "rtf":"Documents",
    "ppt":"Documents",
    "key":"Documents",
    "odp":"Documents",
    "pps":"Documents",
    "ods":"Documents",
    "odt":"Documents",
}
